apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-p4vj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-p4vj
    app.kubernetes.io/part-of: e2e-nodejs
  name: devfile-sample-p4vj
  namespace: e2e-demos-tzfj-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-p4vj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-p4vj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected@sha256:ffec2bc0b3ac1be6cd12a4cc4952131fd02a962e3f211b952e67c8c46065089f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
